version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./:/var/app
    networks:
      - workspace
    env_file:
      - .env

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django_db
    networks:
      - workspace

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - workspace


networks:
  workspace:
