version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./:/var/app
    networks:
      - workspace
    env_file:
      - .env

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django_db
    networks:
      - workspace

networks:
  workspace:
